name: keycloak_dart
description: A Keycloak adapter for AngularDart
version: 0.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.4
