name: angular_keycloak
description: Keycloak for AngularDart
version: 0.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

dev_dependencies:
  build_runner: ^1.5.2
  build_test: ^0.10.8
  # Avoid upgrading build_web_compilers to ^2.0.0 until
  # https://github.com/dart-lang/build/issues/2266 is fixed.
  build_web_compilers: ^1.2.2
  test: ^1.6.3
