name: angular_keycloak
description: Keycloak for AngularDart
version: 0.1.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  angular_router: ^2.0.0-alpha+21

  keycloak:
    git: https://github.com/itbh-at/keycloak.git

dev_dependencies:
  build_runner: ^1.5.2
  build_test: ^0.10.8
  build_web_compilers: ^1.2.2
  test: ^1.6.3
