name: angular_keycloak
description: Keycloak for AngularDart
version: 0.2.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  angular: ^6.0.0-alpha+1
  angular_router: ^2.0.0-alpha+22

  keycloak:
    git: https://github.com/itbh-at/keycloak.git

dev_dependencies:
  angular_components: ^0.14.0-alpha+1
  angular_test: ^2.3.0
  build_runner: ^1.6.5
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  mockito: ^4.1.0
  test: ^1.6.3
