name: angular_keycloak
description: Keycloak for AngularDart
version: 0.2.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  angular: ^6.0.0
  angular_router: ^2.0.0

  keycloak:
    git: https://github.com/itbh-at/keycloak.git

dev_dependencies:
  angular_components: ^1.0.2
  angular_test: ^3.0.0
  build_runner: ^1.10.2
  build_test: ^1.2.2
  build_web_compilers: ^2.11.0
  mockito: ^4.1.2
  test: ^1.15.4
