library dart_keycloak;

export 'src/keycloak_service.dart';

//TODO: Cannot have @JS("Keycloak") at the head of the generated binding
//TODO: Need to fix the one line syntax error generated by facade
//TODO: Must pass in 'promiseType':'native' in init()
